lexops <- tibble(string = dat$string,
                  Length = dat$Length,
                  PoS.SUBTLEX_UK = dat$subtlex_uk.DomPoS,
                  PoS.BNC.Written = dat$bnc.wDomPoS,
                  PoS.BNC.Spoken = dat$bnc.sDomPoS,
                  PoS.ELP = dat$elp.DomPoS,
                  Syllables = dat$mhyph.syllables,
                  Zipf.SUBTLEX_UK = dat$subtlex_uk.zipf,
                  Zipf.SUBTLEX_US = dat$subtlex_us.zipf,
                  Zipf.BNC.Spoken = dat$bnc.sZipf,
                  Zipf.BNC.Written = dat$bnc.wZipf,
                  Zipf.Mean = dat$Mean.Zipf,
                  fpmw.SUBTLEX_UK = dat$subtlex_uk.fpmw,
                  fpmw.SUBTLEX_US = dat$subtlex_us.fpmw,
                  fpmw.BNC.Spoken = dat$bnc.sFpmw,
                  fpmw.BNC.Written = dat$bnc.wFpmw,
                  fpmw.Mean = dat$Mean.fpmw,
                  BG.SUBTLEX_UK = dat$subtlex_uk.bg,
                  BG.SUBTLEX_US = dat$subtlex_us.bg,
                  BG.BNC.Spoken = dat$bnc.sbg,
                  BG.BNC.Written = dat$bnc.wbg,
                  BG.Mean = dat$Mean.bg,
                  ON.OLD20 = dat$old20,
                  ON.Colthearts_N = dat$coltheart.N,
                  ON.Log_OLD20 = log(dat$old20),
                  ON.Log_Colthearts_N = log(dat$coltheart.N),
                  FAM.Glasgow_Norms = dat$gn.FAM,
                  FAM.Clark_and_Paivio = dat$cp.FAM,
                  AoA.Kuperman = dat$kuperman.AOA,
                  AoA.Glasgow_Norms = dat$gn.AOA,
                  CNC.Brysbaert = dat$brysbaert.CNC,
                  CNC.Glasgow_Norms = dat$gn.CNC,
                  AROU.Warriner = dat$warriner.AROU,
                  AROU.Glasgow_Norms = dat$gn.AROU,
                  VAL.Warriner = dat$warriner.VAL,
                  VAL.Glasgow_Norms = dat$gn.VAL,
                  DOM.Warriner = dat$warriner.DOM,
                  DOM.Glasgow_Norms = dat$gn.DOM,
                  IMAG.Glasgow_Norms = dat$gn.IMAG,
                  IMAG.Clark_and_Paivio = dat$cp.IMAG,
                  SIZE.Glasgow_Norms = dat$gn.SIZE,
                  GEND.Glasgow_Norms = dat$gn.GEND,
                  BLP.RT = dat$blp.rt,
                  BLP.RT.zscore = dat$blp.rt.zscore,
                  BLP.Accuracy = dat$blp.accuracy,
                  ELP.RT = dat$elp.rt,
                  ELP.RT.zscore = dat$elp.rt.zscore,
                  ELP.Accuracy = dat$elp.accuracy)


# Visualilsation vector categories
vis.cats <- c('Length', 'Syllables', 'Part of Speech', 'Word Frequency', 'Bigram Frequency', 'Orthographic Neighbourhood', 'Familiarity', 'Age of Acquisition', 'Concreteness', 'Arousal', 'Valence', 'Dominance', 'Imageability', 'Semantic Size', 'Semantic Gender', 'Lexical Decision Response Time', 'Lexical Decision Accuracy')

visualise.opts <- names(lexops)[!(names(lexops) %in% c('string'))]

vis.opt.2.source <- function(x){switch(x,
                                       '(None)' = '',
                                       'Target Word' = '',
                                       'Suggested Matches' = '',
                                       'Part of Speech' = visualise.opts[grepl("PoS",visualise.opts)],
                                       'Length' = 'Length',
                                       'Syllables' = 'Syllables',
                                       'Word Frequency' = visualise.opts[grepl("Zipf",visualise.opts) | grepl("fpmw",visualise.opts)],
                                       'Bigram Frequency' = visualise.opts[grepl("BG",visualise.opts)],
                                       'Orthographic Neighbourhood' = visualise.opts[grepl("ON",visualise.opts)],
                                       'Familiarity' = visualise.opts[grepl("FAM",visualise.opts)],
                                       'Age of Acquisition' = visualise.opts[grepl("AoA",visualise.opts)],
                                       'Concreteness' = visualise.opts[grepl("CNC",visualise.opts)],
                                       'Arousal' = visualise.opts[grepl("AROU",visualise.opts)],
                                       'Valence' = visualise.opts[grepl("VAL",visualise.opts)],
                                       'Dominance' = visualise.opts[grepl("DOM",visualise.opts)],
                                       'Imageability' = visualise.opts[grepl("IMAG",visualise.opts)],
                                       'Semantic Size' = visualise.opts[grepl("SIZE",visualise.opts)],
                                       'Semantic Gender' = visualise.opts[grepl("GEND",visualise.opts)],
                                       'Lexical Decision Response Time' = visualise.opts[grepl("RT",visualise.opts)],
                                       'Lexical Decision Accuracy' = visualise.opts[grepl("Accuracy",visualise.opts)]
)}